# Generated by Django 4.2.9 on 2024-01-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(max_length=50),
        ),
    ]
