# Generated by Django 4.2.9 on 2024-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="User", max_length=50),
        ),
    ]
