# Generated by Django 4.2.9 on 2024-01-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("User", "User")], max_length=50
            ),
        ),
    ]
